{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "pegasus.ipynb",
      "provenance": [],
      "mount_file_id": "1gCNqANiCfVKcfIB6qIGuLaqfTWPO6Ent",
      "authorship_tag": "ABX9TyMcJyMY1wgvlOAsOMsfL63E",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/thangarani/project/blob/master/pegasus_extractive_vs_abstractive.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "ev17iWVNGt_Z",
        "colab_type": "text"
      },
      "source": [
        "Pegasus - Extractive Vs Abstractive Summarization\n",
        "\n",
        "---\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "6cHskLpc_ed9",
        "colab_type": "text"
      },
      "source": [
        "Text summarization is the task of shortening a given text yet retaining the essential gist of the entire document. Summarization is usually seen to be broadly divided into two categories Extractive and Abstractive.\n",
        "\n",
        "**Extractive** summarization can be seen as the task of ranking and scoring sentences in the document based on certain metrics and then picking top-k sentences as the representative summary of the input the document, whereas, \n",
        "\n",
        "**Abstractive** summarization can be seen as a technique in which the summary is generated by generating novel sentences by either rephrasing or using the new words, instead of simply extracting the important sentences generating a summary of the input document yet retaining the main essence of the document and being linguistically correct at the same time.."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Eg-TYzHJG_nE",
        "colab_type": "text"
      },
      "source": [
        "Clone [Pegasus-demo](https://github.com/TheRockXu/pegasus-demo.git) project"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "HaTNrunmck8b",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 101
        },
        "outputId": "e9d12a40-38f4-4a46-8f5b-2d331048f842"
      },
      "source": [
        "!git clone https://github.com/TheRockXu/pegasus-demo.git"
      ],
      "execution_count": 15,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Cloning into 'pegasus-demo'...\n",
            "remote: Enumerating objects: 230, done.\u001b[K\n",
            "remote: Total 230 (delta 0), reused 0 (delta 0), pack-reused 230\u001b[K\n",
            "Receiving objects: 100% (230/230), 1.86 MiB | 537.00 KiB/s, done.\n",
            "Resolving deltas: 100% (82/82), done.\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "beKipkcXKR-N",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "d2167211-7974-4104-ca2d-d7456c48841f"
      },
      "source": [
        "cd /content/pegasus-demo "
      ],
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "/content/pegasus-demo\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "9jWzg4_XKY22",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "fc5a6bdf-866c-4948-b745-dc3b9b709ec9"
      },
      "source": [
        "mkdir model"
      ],
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "mkdir: cannot create directory ‘model’: File exists\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ZJOKzoopcvCY",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "cd /content/pegasus-demo/model/"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "tJ9P2MWDJa7F",
        "colab_type": "text"
      },
      "source": [
        "Pretrained Model\n",
        "\n",
        "---\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "lD-Jaaq2i-8g",
        "colab_type": "text"
      },
      "source": [
        "I uploaded the pretrained model to my Google drive, so i am doing copy and paste from there. For you, please download the pretrained cnn_dailymail and gigaword model directly from https://drive.google.com/file/d/1FVzZto4bf5_TCmRy3tNeirhPDdLrvum5/view and https://drive.google.com/file/d/1ZF2qO6bAnsTF2LSndLMir3e7NrlFL288/view respectively. Unzip it and put it to model/"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "xnXswnZbdIH6",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "cp /content/drive/My\\ Drive/Colab\\ Notebooks/gigaword.tar.xz ."
      ],
      "execution_count": 18,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "l15ZC0aUrFYZ",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "cp /content/drive/My\\ Drive/Colab\\ Notebooks/cnn_dailymail.xz ."
      ],
      "execution_count": 19,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "rt2OgvfsJ6Wb",
        "colab_type": "text"
      },
      "source": [
        "Install sentence piece"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "B9svfRxZexF_",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "96bb2890-5ea3-4836-fa3d-f5781610a502"
      },
      "source": [
        "!pip install sentencepiece"
      ],
      "execution_count": 20,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: sentencepiece in /usr/local/lib/python3.6/dist-packages (0.1.91)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "vRKvGYzWJ_HI",
        "colab_type": "text"
      },
      "source": [
        "Install xz-utils unzip"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7ku19MIQh3vO",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 151
        },
        "outputId": "8b74ad55-9d0c-48f4-bda6-9b94effa4c77"
      },
      "source": [
        "!sudo apt install xz-utils"
      ],
      "execution_count": 21,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Reading package lists... Done\n",
            "Building dependency tree       \n",
            "Reading state information... Done\n",
            "xz-utils is already the newest version (5.2.2-1.3).\n",
            "The following package was automatically installed and is no longer required:\n",
            "  libnvidia-common-440\n",
            "Use 'sudo apt autoremove' to remove it.\n",
            "0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "QCPOug_fiJoX",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "fc2f0732-b518-442d-c814-f35f4eb6ae92"
      },
      "source": [
        "cd /content/pegasus-demo/model/"
      ],
      "execution_count": 23,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "/content/pegasus-demo/model\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "zarztrrHic-H",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "034d7ae2-ddf1-485b-bf11-b3b503dbc199"
      },
      "source": [
        "ls"
      ],
      "execution_count": 34,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "\u001b[0m\u001b[01;34m1595095633\u001b[0m/  cnn_dailymail.xz  gigaword.tar.xz\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "wAM8627y_1XS",
        "colab_type": "text"
      },
      "source": [
        "# ***Extractive Summarization***\n",
        "\n",
        "---\n",
        "\n",
        "\n",
        "\n",
        "---\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "JIWmnFMIKoZs",
        "colab_type": "text"
      },
      "source": [
        "Cnn_Dailymail\n",
        "---\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "pQIonnXTr2V-",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 101
        },
        "outputId": "075a8b35-ae5b-47c3-9c1b-0bcc6ab34a09"
      },
      "source": [
        "!tar -xvf cnn_dailymail.xz"
      ],
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "1595037231/\n",
            "1595037231/saved_model.pb\n",
            "1595037231/variables/\n",
            "1595037231/variables/variables.data-00000-of-00001\n",
            "1595037231/variables/variables.index\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ZBgD2jJRnC3R",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "74ff3be9-0635-43f1-b1e8-654d1d8233fd"
      },
      "source": [
        "cd /content/pegasus-demo"
      ],
      "execution_count": 26,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "/content/pegasus-demo\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "THG0yRPa8Dtu",
        "colab_type": "text"
      },
      "source": [
        "Example\n",
        "\n",
        "---\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "V3IDlu25szOz",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 608
        },
        "outputId": "d0c6618a-62dd-45fb-a483-ccc67a720552"
      },
      "source": [
        "!python test_example.py --article example_article --model_dir /content/pegasus-demo/model/1595037231/ --model_name cnn_dailymail"
      ],
      "execution_count": 37,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "2020-08-05 08:19:20.047703: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\n",
            "2020-08-05 08:19:25.002159: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1\n",
            "2020-08-05 08:19:25.069711: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
            "2020-08-05 08:19:25.069804: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a5c8dd530367): /proc/driver/nvidia/version does not exist\n",
            "2020-08-05 08:19:25.129665: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz\n",
            "2020-08-05 08:19:25.130056: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2b5aa00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
            "2020-08-05 08:19:25.130101: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "2020-08-05 08:19:26.564209: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 393637888 exceeds 10% of free system memory.\n",
            "2020-08-05 08:19:26.565099: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "2020-08-05 08:19:26.595409: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "2020-08-05 08:19:26.677539: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "2020-08-05 08:19:26.708210: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "\n",
            "PREDICTION >>  The hacking group known as NC29 is largely believed to operate as part of Russia's security services .<n>The three countries allege that it is carrying out a persistent and ongoing cyber campaign to steal intellectual property about a possible coronavirus vaccine .\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "NkRn3JYNB1xl",
        "colab_type": "text"
      },
      "source": [
        "# ***Abstractive Summarization***\n",
        "---\n",
        "\n",
        "\n",
        "\n",
        "---"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "5cuKDY2p8dgz",
        "colab_type": "text"
      },
      "source": [
        "# Gigaword"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "C6v9Fosvie3V",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 101
        },
        "outputId": "617e89b6-178b-4587-bd4f-b82dd5f0d388"
      },
      "source": [
        "!tar -xvf gigaword.tar.xz"
      ],
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "1595095633/\n",
            "1595095633/saved_model.pb\n",
            "1595095633/variables/\n",
            "1595095633/variables/variables.data-00000-of-00001\n",
            "1595095633/variables/variables.index\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "NbETTGpYqKbG",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "outputId": "d81bcd62-e180-43d6-ce86-837b04160626"
      },
      "source": [
        "cd /content/pegasus-demo"
      ],
      "execution_count": 36,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "/content/pegasus-demo\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "O_N9WuYIBF6A",
        "colab_type": "text"
      },
      "source": [
        "Example\n",
        "\n",
        "---\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Fe0AMMu3qHn4",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 608
        },
        "outputId": "a473936a-c1a5-4b5e-ef5b-56b4127c172d"
      },
      "source": [
        "!python test_example.py --article example_article --model_dir /content/pegasus-demo/model/1595095633/ --model_name gigaword"
      ],
      "execution_count": 29,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "2020-08-05 08:08:16.504598: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1\n",
            "2020-08-05 08:08:20.862217: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1\n",
            "2020-08-05 08:08:20.967088: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
            "2020-08-05 08:08:20.967197: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a5c8dd530367): /proc/driver/nvidia/version does not exist\n",
            "2020-08-05 08:08:21.036173: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz\n",
            "2020-08-05 08:08:21.036675: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2482a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
            "2020-08-05 08:08:21.036730: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "2020-08-05 08:08:22.655234: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 393637888 exceeds 10% of free system memory.\n",
            "2020-08-05 08:08:22.658584: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "2020-08-05 08:08:22.728705: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "2020-08-05 08:08:22.909967: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "2020-08-05 08:08:22.980991: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16777216 exceeds 10% of free system memory.\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'embeddings/weights:0' shape=(96103, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/beta:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/LayerNorm/gamma:0' shape=(1024,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/q_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'encoder/layer_0/self_attention/k_proj/kernel:0' shape=(1024, 1024) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().\n",
            "\n",
            "PREDICTION >>  three countries allege thatCozy Bear is trying to steal vaccine research\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Z_6bwqBRIiiQ",
        "colab_type": "text"
      },
      "source": [
        "Reference:\n",
        "https://github.com/google-research/pegasus/issues/13 , https://github.com/google-research/pegasus/issues/63"
      ]
    }
  ]
}